"""context-router-adapters-copilot: GitHub Copilot agent adapter.

Generates `.github/copilot-instructions.md` content and per-mode agent
instruction files from a ContextPack.
"""

from __future__ import annotations

from contracts.models import ContextItem, ContextPack

_MODE_HEADER = {
    "review": (
        "When reviewing code in this repository, focus on the files and "
        "symbols listed below. They represent the highest-impact changes "
        "and their blast radius."
    ),
    "implement": (
        "When implementing features in this repository, use the entry "
        "points, contracts, and extension points listed below as the "
        "primary integration surface."
    ),
    "debug": (
        "A failure has been detected. The files and signals below are the "
        "most likely root-cause sites. Start your investigation there."
    ),
    "handover": (
        "You are continuing work on this repository. The context below "
        "captures recent changes, project memory, and key decisions."
    ),
}

_SOURCE_EMOJI = {
    "changed_file": "✏️",
    "blast_radius": "💥",
    "impacted_test": "🧪",
    "config": "⚙️",
    "entrypoint": "🚪",
    "contract": "📄",
    "extension_point": "🔌",
    "file": "📁",
    "runtime_signal": "🔴",
    "failing_test": "❌",
    "memory": "🧠",
    "decision": "📝",
}


def _fmt_item(item: ContextItem) -> str:
    emoji = _SOURCE_EMOJI.get(item.source_type, "•")
    lines = [f"- {emoji} **{item.title}**"]
    if item.reason:
        lines.append(f"  - _{item.reason}_")
    if item.excerpt:
        lines.append(f"  - Confidence: {item.confidence:.0%}")
    return "\n".join(lines)


class CopilotAdapter:
    """Agent adapter that generates GitHub Copilot instructions content.

    Call `generate()` for the main `.github/copilot-instructions.md` content.
    The output is a Markdown document consumable by GitHub Copilot's
    repository-level instructions feature.
    """

    def generate(self, pack: ContextPack) -> str:
        """Generate Copilot instructions content from a ContextPack.

        Args:
            pack: The ranked context pack to render.

        Returns:
            Markdown string for .github/copilot-instructions.md.
        """
        intro = _MODE_HEADER.get(pack.mode, f"Task mode: {pack.mode}")
        lines: list[str] = [
            "# context-router — Copilot Instructions",
            "",
            f"**Mode:** {pack.mode.capitalize()}",
        ]

        if pack.query:
            lines += [f"**Task:** {pack.query}", ""]
        else:
            lines.append("")

        lines += [
            intro,
            "",
            f"> Token budget: ~{pack.total_est_tokens:,} tokens "
            f"({pack.reduction_pct:.0f}% reduction from full codebase scan)",
            "",
            "## Prioritised Context",
            "",
        ]

        if not pack.selected_items:
            lines.append("_Run `context-router index` to populate context._")
        else:
            # Group items by source_type for readability
            by_type: dict[str, list[ContextItem]] = {}
            for item in pack.selected_items:
                by_type.setdefault(item.source_type, []).append(item)

            for source_type, items in by_type.items():
                section_title = source_type.replace("_", " ").title()
                lines += [f"### {section_title}", ""]
                for item in items:
                    lines.append(_fmt_item(item))
                lines.append("")

        lines += [
            "---",
            "_Generated by [context-router](https://github.com/mohankrishnaalavala/context-router)._",
        ]
        return "\n".join(lines)
